# Generated by Django 6.0.6 on 2026-07-04 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('scope_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16)),
                ('rrule', models.TextField(blank=True, default='')),
                ('recurrence_type', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='calendar.event')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rsvp', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('tentative', 'Tentative'), ('declined', 'Declined')], default='invited', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calendar.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['user', 'weekday'], name='cal_avail_user_weekday')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'start'], name='cal_event_owner_start'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['scope_key', 'start'], name='cal_event_scope_start'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['recurrence_parent'], name='cal_event_parent'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence_parent__isnull', False)), fields=('recurrence_parent', 'start'), name='cal_event_uniq_occurrence'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user'], name='cal_participant_user'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='cal_participant_uniq'),
        ),
    ]
